### ISSUE TITLE
CHRIMEN Board 発売記念イベント 企画

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#109]
- 対象
  - CHRIMEN Board 購入者
  - CHRIMEN Board に興味のある方
- 日時
- 場所候補
  - mixi & Switch Science エイドステーション サービス利用
  - 秋葉原 イベントスペース（各種部品購入は各自）
    - 良い場所の提案大募集
- イベント内容案
  - ファームウェアアップデート・ハンズオン
  - ハンズオン
  - ~~ハッカソン~~

---
### TODO
- [x] [CHIRIMEN ボード ハンズオン リンク](http://chirimen-oh.connpass.com/event/37934/)
- [x] 日時：2016/09/17(土) 10:00-
- [x] 場所：[秋葉原 永和システムマネジメントのコワーキングスペース](https://www.doorkeeper.jp/%E4%BC%9A%E5%A0%B4/eiwa-systems-management)
- [x] connpass グループ作成 #122 done.
- [x] connpass イベント作成 #123 
- [x] connpass イベントハッシュタグ 
  - 案：ChirimenBoard
  - ~~案：CHIRIMEN_OH~~
- [x] [物品リストの作成](https://drive.google.com/open?id=1g7p_MyabQ4hA8-tlhNRR5bjSiRT9UsMtoC0xYHTndz0)  #126 done.
  - [x] 会場利用可能機材リスト作成（テーブルや電源タップ等）
  - [x] 会場持ち込み機材リスト作成（テーブルや電源タップ等）
  - [x] 部材買い出しツアーリスト #134 done. 09/16
- [x] イベント内容検討・作成
  - ~~案：もくもく会？~~
  - ~~案：Hello Real world？~~ #116 
  - ~~案：LEDと超音波センサー + ブレッドボード？~~
  - タクトスイッチとLEDを使ったアプリ作成。  
  -  [x] 上記ハンズオンコードを作成する人が必要。  
    => fabble を活用
- [x] タイムスケジュール作成（暫定）
  - 10:00 開場
  - 10:30 オープニング
  - 10:40 ファームウェアハンズオン
  - 13:00 アプリ開発ハンズオン
    - タクトスイッチとLEDを使ったアプリ作成。  
  - 18:30 懇親会
  - 20:00 撤収
- [x] 人数調整
  - 購入者枠：10人
  - 購入済枠：10人
  - チューター枠：10人
  - 合計：30人
- [x] エイドステーション
  - 手配機材
    - CHRIMEN ボード
    - ブレッドボード
    - ジャンパーピン
  - [x] CHIRIMENボードも申請対象か確認 => 必要
  - [x] サービス利用有無の判定 => 利用する
  - [x] 手配機材の選定 09/01 done.
  - [x] 申請手続き 09/01 done.

**Comment by sizuhiko** [comment]
秋葉原でのイベントスペース、永和システムマネジメントのコワーキングスペースが利用可能です。
https://www.doorkeeper.jp/%E4%BC%9A%E5%A0%B4/eiwa-systems-management

**Comment by ghost** [comment]
CHIRIMENは購入できますか?

**Comment by gurezo** [comment]
スイッチサイエンスさんに残りの在庫や販売に関して、確認しないと分からない状況です。

**Comment by gurezo** [comment]
> CHIRIMENは購入できますか?  

イベントページ通り、10 枚？台？販売予定です。

**Comment by ghost** [comment]
なんとなく、イベントの告知(connpassへのリンク)がないなぁ、と思いました。

facebook
google calendar
slackの#sale_aniversaryのtopic
twitter

にはあるのですが、知らない・参加していない人でも見えるのはぎりぎりtwitterくらいで、それも流れてしまうような気がします。 (見落としていなければ、このissueにも書いてない、ような)

参加するような人はだいたいどれかは見ているので大丈夫、なんですかね。

**Comment by MSakamaki** [comment]
connpassへのリンクは確かに無いですね、自分も良く探すのでとりあえずコメントに投稿しておきます。

http://chirimen-oh.connpass.com/event/37934/

**Comment by MSakamaki** [comment]
facebookはトップへ固定できる投稿があるので、そこにサマリを常に置いてメンテするように運用するのはどうでしょう？

**Comment by gurezo** [comment]
[CHRIMEN Board 発売記念イベント 情報 追記 #55](https://github.com/chirimen-oh/chirimen-oh.github.io/issues/55) サイト上に告知情報追加しました。
ツイッターの方も、日に１回カウントダウンツイートするようにします。

**Comment by dynamis** [comment]
何度かお話ししましたが、先日お手伝いいただいた中央大学集中講義 (#118 ありがとうございました！) の最終日 (成果発表含む) がちょうどこのイベント日に重なっております。
両者都合が良ければということで少しお話ししていましたが、人数的に許容できるようであれば中央大学の学生 (8名 + 講師 3名) も当日同じスペースの一部をお借りして、発売記念イベントのハンズオン最後あたりに少し学生さんの発表タイムを頂けないでしょうか。(参加人数など見ながら一緒にやるかは来週金曜時点で最終確定だが基本的にはなるべくご一緒したい方向です)。

ご検討ください。

**Comment by gurezo** [comment]
@dynamis さん、個人的な見解ですが現時点（2016/09/10 21:39）の
参加人数であれば、ご一緒して良いと思っております。

**Comment by gurezo** [comment]
@dynamis さん、09/17は、ご一緒する場合、どのタイミングで合流でしょうか？
1. 10:00- ：ハンズオンイベント開始時間
2. 13:30-：中央大学の演習開始時間

**Comment by dynamis** [comment]
タイミングについては CHIRIMEN 側のイベントに時間を揃えて 13:00 開始で考えています。

**Comment by gurezo** [comment]
@dynamis さん
成果発表後に行う懇親会は、中央大学生に関して、どのようにお考えですか？
1. 会費徴収の上、参加
2. 会費徴収無料で参加
3. 懇親会不参加
4. 上記以外のパターン

**Comment by dynamis** [comment]
学生さん達は 13:00 同時に開始、17:00 から成果発表をさせてもらい、懇親会については学生さんの参加自由とし、参加した人の参加費は授業側の予算で出します。
赤塚さんの方でもその方向で調整してくれていると聞きましたので、土曜はそんな感じでご一緒させてくださいませ。

**Comment by gurezo** [comment]
承知しました。
現時点のconnpassの参加人数も受け入れ大丈夫だと思います。

**Comment by gurezo** [comment]
部材買い出しツアーリストdone. 09/16

**Comment by gurezo** [comment]
皆様、お疲れ様でした。
皆様のさぽーとに感謝です。
無事にイベントを終了したので、close
