### ISSUE TITLE
タスクリスト

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#17]
超大雑把なタスクリストを書いてみました＠ぐんまー
コミュニティの皆様、適宜アドバイス＆修正をお願いします。
### タスクリスト
- [ ] CHIRIMEN | MDN  
    ※ 現状維持で、ローカライズ実施
- [x] #5 より　facebook group 変更 mozOpenHard => CHIRIMEN Open Hardware  
    ※グループ名は変更済み 4/16 done.　@dadaa  
    ※urlは、現在回答待ち  4/16 23:27時点 @dadaa
- [x] #5 よりslack 作成 CHIRIMEN Open Hardware  
    ※ https://chirimenopenhardware.slack.com 作成 @gurezo 04/16 done.  
  　　　~~=> mozOpenHard の slack が、リネーム出来るかもしれない 連絡待ち 4/18~~  
  　　　**=> mozOpenHard の slack リネームする @dadaa  4/18 done.**  
  　　　**=> 上記作業後、[https://chirimenopenhardware.slack.com](https://chirimenopenhardware.slack.com) を削除 @gurezo 4/19 done.**  
- [x] twitter アカウント作成 @gurezo 04/16
- [ ] #11 よりCHRIMENアイコン作成  
    ※現状は、foxfoodイメージから切り抜き活用中
- [ ] [tumblr：mozOpenHard](http://is.gd/5hzvBf)  
  - [ ] 上記サイト削除タイミング 日程要検討
  - [x] #1 より 移行サイト [https://chirimen-org.github.io/](https://chirimen-org.github.io/) 作成中 @MSakamaki  
- [ ] [Fabble - ChirimenEdu](http://fabble.cc/chirimenedu)　　
  - [X] 現行のまま
  - [ ] B2G ver 2.5 or ver 2.6 で、再動作検証が必要 @naokisekiguchi 
- [x] gmail アカウント作成 @gurezo 04/16 done. 
- [x] 一般用Google Group作成 @gurezo 04/16 done. 
- [x] スタッフ用Google Group作成 @gurezo 04/16 done.

**Comment by ghost** [comment]
> 一般用Google Group作成 @gurezo 04/16 done.
>  スタッフ用Google Group作成 @gurezo 04/16 done.

https://groups.google.com/forum/#!forum/mozopenhard はどうなりますでしょか

**Comment by gurezo** [comment]
これは、今さっきmozOpenHardのGoogle Group の存在を知ったので、
現時点でのオーナー権限のある方にお願いします。
ただ、そこでの議論は、残した方／引っ越しが良いとは思います。

**Comment by dadaa** [comment]
CHIRIMEN | MDN の問題を除いて，issue 登録があるので，CHIRIMEN | MDN を issue とし，これを閉じます
