### ISSUE TITLE
IEEE Tokyo Young Professionals hackathon (7/8-9)

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#187]
## issue purpose
- イベント開催に向けての準備
- http://sites.ieee.org/sb-keio/ieee-hackathons-2017/

## Close conditions
- [x] 日程：7/8(土)-9(日)
- [x] タイムスケジュール
- [x] 物品リスト

**Comment by sizuhiko** [comment]
調整さん
https://chouseisan.com/s?h=3a7ef91d029e426784075aa425e73959

**Comment by TakehiroSato** [comment]
先日はコミュニティミーティングに参加させていただき、誠にありがとうございました。
本イベントの開催にご協力をいただき、厚く御礼申し上げます。

現在Tokyo YP側でも、イベントの各日程候補につきましてメンバーの予定を調整しております。
5/2(火)頃を目処に双方の予定を付き合わせ、日程を決定できればと考えております。
何卒よろしくお願いいたします。

**Comment by gurezo** [comment]
7/8(土)-9(日)に開催予定＠Slackより

**Comment by gurezo** [comment]
スタッフ向け事前講習 調整さん
https://chouseisan.com/s?h=5828b6a1b33f41f0b13082d93956f911

**Comment by gurezo** [comment]
### スタッフ向け事前講習日
- [x] 6/3(土) 13:30〜	
- TODO
  - [x] 講習内容 (@gurezo さん)
  - [x] 参加者数 (@TakehiroSato さん?)
  - [ ] 機材

**Comment by ghost** [comment]
6/3事前講習を午前からやる？

**Comment by gurezo** [comment]
(1) GROVE I2C タッチセンサ
(2) GROVE I2C 三軸加速度センサ ADXL345搭載 v1.3
(3) GROVE I2C デジタル光センサ
(4) 超音波センサ SRF02
(5) ADT7410使用 温度センサモジュール
(6) 赤色LED
(7) shield 10個

5/25 MJ搬入完了 @naokisekiguchi

**Comment by gurezo** [comment]
TODO:講習内容 gist @gurezo

**Comment by gurezo** [comment]
フライヤー
http://sites.ieee.org/sb-keio/files/2017/05/tokyoYP_hack2017_v1_1.pdf

**Comment by gurezo** [comment]
#### 事前講習タイムテーブルドラフト
- [IEEEBeforeEvent.md ](https://gist.github.com/gurezo/f327dce809151ba7c5920f735616458a)

**Comment by gurezo** [comment]
```
皆様、6/3(土)の事前講習会の参加者ですが、合計で【8名】となりました。
（すべてIEEE Tokyo YPのメンバーです）
GitHubに作成していただいたドラフトのページを参考に、環境設定を進めさせます。

今回講習を受けさせていただくYPメンバーが、7/8-9の本番で、各チームに入ってサポートができるようにしたいと考えております。
何卒よろしくお願いいたします。
```
slack より転機@5/29 21:39

**Comment by gurezo** [comment]
```
合計で【9名】
```
slack より転機 5/31 15:32

**Comment by gurezo** [comment]
### 6/3(土) タイムテーブル

|time | contents | by　| TODO |
|:----|:----|:----|:----|
|10:00 - | 開場 | [@kudodo](https://github.com/kudodo) , <br>[@gurezo](https://github.com/gurezo) | 入室 |
|10:15 - 10:30 | 開催前準備 |  [@kudodo](https://github.com/kudodo) , <br>[@gurezo](https://github.com/gurezo), anybody | 機材セッティング |
|10:30 - 11:00 | 受付開始 | TBD |
|11:00 - 11:10 | 始めの挨拶・会場説明 <br>(wifiなど) | [@gurezo](https://github.com/gurezo) |
|11:10 - 12:00 | 開発環境準備 | 全員 |
|12:00 - 13:00 | 昼食 | 各自適宜 |
|13:00 - 13:30 | Hello Worldまで | [@gurezo](https://github.com/gurezo) | |
|13:30 - 15:00 | [example LEDBlink](https://github.com/chirimen-oh/examples/tree/forCMN2015-1_B2GOS-20170301/LEDblink) | [@gurezo](https://github.com/gurezo) | |
|15:00 - 15:15 | 15分休憩 | | |
|15:15 - 18:00 | (1)~(5)いずれかのexample | 各自 | | |
|18:00 - 19:00 | 後片付け・整理 | 全員 | | |
|19:00 | 撤収 | 全員 | | |

### 対象センサー

```
(1) GROVE I2C タッチセンサ
(2) GROVE I2C 三軸加速度センサ ADXL345搭載 v1.3
(3) GROVE I2C デジタル光センサ
(4) 超音波センサ SRF02
(5) ADT7410使用 温度センサモジュール
```

### 用意するもの

* ノートPC
  - Firefoxブラウザ(最新Ver.)をインストールしておいてください。
  - https://www.mozilla.org/ja/firefox/new/
  - 2017.5.27 時点の最新は Ver. 53.0.3

### 対象OS

Firefoxブラウザ(最新Ver.)をインストールできるOS

- Windows 7 以降
- Mac OS X v10.6 Snow Leopard 以降
- Linux (Ubuntu 12.04 以降推奨)

### TODO
- [x] CHIRIMEN ボード数量確認 5/25
- [ ] 最新ファームウェア焼き込み（20枚？）
- [ ] CHIRIMEN ボード動作確認
- [ ] touch & try 機材数量チェック
- [ ] カリキュラムチェック

### CHIRIMENへのドングルの接続
* CHIRIMENへのドングルの接続方法はこちらをご参照ください。
https://chirimen.org/docs/ja/basic_startup.html

### CHIRIMEN起動、そして、Wi-Fi設定
* CHIRIMENを起動します。詳しくは、こちら
https://chirimen.org/docs/ja/basic_startup.html#tocAnchor-1-1-3

* 起動後、Settingアプリ(画面上の歯車アイコン）を開き、Wi-Fi を選択。
* 画面上部のWi-Fi をタップして ON に切り替え、<br>利用可能なネットワークをタップしてネットワークに接続。
* ネットワークが保護されている場合は、パスワードを入力する必要があります。<br>詳しくは、ネットワーク管理者に聞いてください。
* （インターネットに）正しくつながっているかどうかは、CHIRIMEN UI上のブラウザ等で<br>適当なサイトにアクセスするなどしてご確認ください。

### イベント用教科書
- [CHIRIMEN Hello world](http://qiita.com/kotakagi/items/3a4f7865ab784cd88cdd)
- [CHIRIMEN I2C sensor ](http://qiita.com/kotakagi/items/56bba849295cf4c81d39)
- [CHIRIMENによるWoTサイネージの作り方(part1)](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenWotSignage1.md)
- [CHIRIMENによるWoTサイネージの作り方(part2)](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenWotSignage2.md)
- [CHIRIMENによるWoTサイネージの作り方(part3)](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenWotSignage3.md)
- [CHIRIMENによるWoTサイネージの作り方(part4)](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenWotSignage4.md)
- [CHIRIMENでI2Cのセンサーを使用する（task.jsバージョン）](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenI2cSensors.md)
- [CHIRIMENでサーボモータを使用する（task.jsバージョン）](https://github.com/naokisekiguchi/WoTsignageText/blob/master/chirimenServo.md)
[- CHIRIMENにI2Cデバイスが繋がんない時に確認すること](http://qiita.com/tadfmac/items/8c3e79ed3d95c31ee72d)

**Comment by gurezo** [comment]
【緩募】
~~6/8~~6/3(土)イベントの準備で、CHIRIMENボード（最低9台）にrelease 20170301 版イメージを
焼き込み／書き込みしてくださる方募集しています。
@gurezo が今週平日にやる予定で居ましたが、現在体調を崩して対応が出来ないためです。

**Comment by sizuhiko** [comment]
6/3ですよね？
今日明日で対応可能な人ということか...

**Comment by gurezo** [comment]
6/3が正解です＞＜。

**Comment by WhiteHawk-taka** [comment]
前のハッカソンで一応20170301が焼き済みなはずではないでしょうか

**Comment by gurezo** [comment]
事前講習 done.
当日の覚書はこちら
https://public.etherpad-mozilla.org/p/chirimen-20170603

**Comment by gurezo** [comment]
イベント当日のスタッフ・チューター募集の調整さん
https://chouseisan.com/s?h=4b1e0aef01974246b95f4e6ff49c92d9

**Comment by gurezo** [comment]
イベント当日ですが、慶應義塾大学矢上キャンパスに直接お越しいただけますと幸いです。
今回、大学側の都合により、初日のみ会場が別の部屋になりました。
    《7/8(土)》16-A棟 厚生棟3階 大会議室
    《7/9(日)》14棟 創想館 セミナールーム3（14-203）
https://www.keio.ac.jp/ja/maps/yagami.html

**Comment by gurezo** [comment]
初日午前中の講義資料
https://github.com/gurezo/chirimen-doc/tree/master/ja
[book.pdf](https://github.com/chirimen-oh/any-issues/files/1109077/book.pdf)

pdfの体裁が崩れているのを調整中です。

**Comment by gurezo** [comment]
ネット配布用リンク
https://www.dropbox.com/sh/gkrukylxzs4xscl/AAC7NX7QN-0vOC8BwN-eUhkya?dl=0

**Comment by gurezo** [comment]
イベントサポートスタッフ

|名前|7/8|7/9|
|:----|:----:|:----:|
|@gurezo|O|O|
|@WhiteHawk-taka|△|△|
|@kazygumi|O|X|
|@sizuhiko|O|O|

※△：AM10:00頃入予定
急遽変更の場合は、連絡の上
こちらを編集する。

**Comment by gurezo** [comment]
当日etherpad
https://etherpad.net/p/IEEE_Tokyo

**Comment by gurezo** [comment]
イベントが終了したので、close
